name: Release Pipeline

on:
  push:
    branches:
      - main  # Quando fizer merge de 'develop' para 'main', o release será disparado
    tags:
      - 'v*'  # Também se fizer um push com uma tag, como v1.0.0

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Generate Release Notes
        run: |
          # Gerar notas de release, pode ser customizado
          echo "Release Notes" > release_notes.txt
          echo "Version: ${{ github.ref }}" >> release_notes.txt

      - name: Create Release in GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: release_notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
